# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$status\
$character"""

# Replace the '‚ùØ' symbol in the prompt with something else
[character] # The name of the module we are configuring is 'character'
success_symbol = '\$(bold green)'
error_symbol = '\$(bold red)'


[directory]
style = "blue"
before_repo_root_style = "cyan"
repo_root_style = "bold blue"
truncation_length = 0
truncate_to_repo = false

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[git_commit]
tag_disabled = false

[git_metrics]
disabled = false
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '


[git_status]
style = 'red'
deleted = ""
modified = ""
renamed = ""
staged = ""
stashed = ""
untracked = ""

[status]
disabled = false
symbol = "‚úñ " # "ü§î "if not set, default to '‚ùå'

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
